In [1]:
import numpy as np
np.random.seed(0)

In [2]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

In [3]:
values = np.random.randint(1, 10, size=5)

In [4]:
values

array([6, 1, 4, 4, 8])

In [5]:
compute_reciprocals(values)

array([ 0.16666667,  1.        ,  0.25      ,  0.25      ,  0.125     ])

In [6]:
big_array = np.random.randint(1, 100, size=1000000)

In [7]:
%timeit compute_reciprocals(big_array)

1 loop, best of 3: 2.62 s per loop


In [8]:
print(compute_reciprocals(values))

[ 0.16666667  1.          0.25        0.25        0.125     ]


In [9]:
print(1.0/values)

[ 0.16666667  1.          0.25        0.25        0.125     ]


In [10]:
%timeit (1.0 / big_array)

100 loops, best of 3: 6.38 ms per loop


In [12]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1, 6)

array([1, 2, 3, 4, 5])

In [15]:
Out[12] / Out[13]

array([ 0.        ,  0.5       ,  0.66666667,  0.75      ,  0.8       ])

In [17]:
x = np.arange(9).reshape((3, 3))

In [18]:
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [19]:
theta = np.linspace(0, np.pi, 3)

In [21]:
theta
np.sin(theta)
np.cos(theta)
np.tan(theta)

array([  0.00000000e+00,   1.63312394e+16,  -1.22464680e-16])

In [22]:
x = np.array([-1, 0, 1])

In [23]:
x
np.arcsin(x)
np.arccos(x)
np.arctan(x)

array([-0.78539816,  0.        ,  0.78539816])

In [24]:
import pandas as pd

In [28]:
data = pd.read_csv('data/president_height.csv')

In [29]:
heights = np.array(data['height(cm)'])

In [30]:
print(heights)

[189 170 189 163 183 171 185 168 173 183 173 173 175 178 183 193 178 173
 174 183 183 168 170 178 182 180 183 178 182 188 175 179 183 193 182 183
 177 185 188 188 182 185]


In [31]:
heights.mean()

179.73809523809524

In [32]:
heights.std()

6.9318434427458921

In [33]:
heights.min()

163

In [34]:
heights.max()

193